// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Job            string
	JobProvider    string
	JobProviderFav string
	JobSeeker      string
	JobSeekerFav   string
	JobSkillMap    string
	Person         string
	PersonProfile  string
	RelatedSkills  string
	Skill          string
}{
	Job:            "job",
	JobProvider:    "job_provider",
	JobProviderFav: "job_provider_fav",
	JobSeeker:      "job_seeker",
	JobSeekerFav:   "job_seeker_fav",
	JobSkillMap:    "job_skill_map",
	Person:         "person",
	PersonProfile:  "person_profile",
	RelatedSkills:  "related_skills",
	Skill:          "skill",
}
