// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Job            string
	JobProvider    string
	JobProviderFav string
	JobSeeker      string
	JobSeekerFav   string
	Person         string
	PersonProfile  string
}{
	Job:            "job",
	JobProvider:    "job_provider",
	JobProviderFav: "job_provider_fav",
	JobSeeker:      "job_seeker",
	JobSeekerFav:   "job_seeker_fav",
	Person:         "person",
	PersonProfile:  "person_profile",
}
