// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Job           string
	JobProvider   string
	JobSeeker     string
	JobSkillMap   string
	Person        string
	PersonProfile string
	RelatedSkills string
	Skill         string
}{
	Job:           "job",
	JobProvider:   "job_provider",
	JobSeeker:     "job_seeker",
	JobSkillMap:   "job_skill_map",
	Person:        "person",
	PersonProfile: "person_profile",
	RelatedSkills: "related_skills",
	Skill:         "skill",
}
