# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: make docker-build
      - name: Docker Tag
        run: |
          docker tag jobsgowhere/server ${{ secrets.DOCKER_USER }}/jobsgowhere:${{ github.sha }}
          docker tag jobsgowhere/server ${{ secrets.DOCKER_USER }}/jobsgowhere:pr-latest
      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/jobsgowhere:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/jobsgowhere:pr-latest